# Generated by Django 4.0 on 2021-12-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_listing_bids_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
    ]
