# Generated by Django 4.0 on 2021-12-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_category',
            field=models.CharField(choices=[('none', 'None'), ('book', 'Book'), ('computer', 'Computer'), ('car', 'Car')], default='none', max_length=32),
        ),
    ]
