# Generated by Django 4.0 on 2021-12-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='listing_date',
        ),
    ]
