# Generated by Django 4.0 on 2022-01-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='posted_by',
        ),
    ]
