# Generated by Django 4.0 on 2022-01-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_auction_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchList',
            field=models.BooleanField(default=False),
        ),
    ]
