# Generated by Django 4.0 on 2022-01-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auction_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myAuction', to='auctions.user'),
        ),
    ]
